---
name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sanity-test:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run sanity test
        shell: bash
        run: |
          pip install ansible
          ansible-test sanity -v
