---
name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sanity-tests:
    name: Run sanity tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ansible_collections/bitnik/gridscale
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run sanity tests
        shell: bash
        run: |
          pip install ansible
          cd ansible_collections/bitnik/gridscale
          ansible-test sanity -v
